#!/bin/bash
### BEGIN INIT INFO
# Provides:            xmemcached
# Required-Start:      $syslog
# Required-Stop:       $syslog
# Should-Start:        $local_fs
# Should-Stop:         $local_fs
# Default-Start:       2 3 4 5
# Default-Stop:                0 1 6
# Short-Description:   Start xmemcached daemon
# Description:         Start xmemcached daemon
### END INIT INFO 

SERVICE_PATH="/bin"
SERVICE_NAME="xmemcached"
SERVICE_FILE="$SERVICE_NAME.exe"
CONFIG_FILE="/etc/$SERVICE_NAME/$SERVICE_NAME.conf"
LOCK_FILE="/var/lock/$SERVICE_NAME.lock"
export MONO_OPTIONS=--runtime=v4.0.30319
export LD_LIBRARY_PATH=.:/usr/local/mono/2.8/lib/:$LD_LIBRARY_PATH

case "$1" in
	start)
		if [ -e $LOCK_FILE ]
		then
			echo "Service $SERVICE_NAME is already running"
		else
			echo "Starting $SERVICE_NAME"
			mono-service2 -d:$SERVICE_PATH -l:$LOCK_FILE -m:$SERVICE_NAME $SERVICE_PATH/$SERVICE_FILE -C $CONFIG_FILE
		fi
		;;
		
	debug)
		if [ -e $LOCK_FILE ]
		then
			echo "Service $SERVICE_NAME is already running"
		else
			echo "Starting $SERVICE_NAME in debug mode"
			mono-service2 -d:$SERVICE_PATH -l:$LOCK_FILE -m:$SERVICE_NAME --debug $SERVICE_PATH/$SERVICE_FILE -C $CONFIG_FILE
		fi
		;;
		
	stop)
		if [ -e $LOCK_FILE ]
		then
			echo "Stopping $SERVICE_NAME"
			kill `cat $LOCK_FILE`
			if [ -e $LOCK_FILE ]
			then
				rm $LOCK_FILE
			fi
		else
			echo "Service $SERVICE_NAME does not seem to be running"
		fi
		;;
	
	restart)
		if [ -e $LOCK_FILE ]
		then
			echo "Stopping $SERVICE_NAME"
			kill `cat $LOCK_FILE`
			if [ -e $LOCK_FILE ]
			then
				rm $LOCK_FILE
			fi
		fi
		
		echo "Starting $SERVICE_NAME"
		mono-service2 -d:$SERVICE_PATH -l:$LOCK_FILE -m:$SERVICE_NAME $SERVICE_PATH/$SERVICE_FILE -C $CONFIG_FILE
		;;
	
	force-restart)
		if [ -e $LOCK_FILE ]
		then
			echo "Forcing $SERVICE_NAME to stop"
			kill -s SIGKILL `cat $LOCK_FILE`
			if [ -e $LOCK_FILE ]
			then
				rm $LOCK_FILE
			fi
		fi
		
		echo "Starting $SERVICE_NAME"
		mono-service2 -d:$SERVICE_PATH -l:$LOCK_FILE -m:$SERVICE_NAME $SERVICE_PATH/$SERVICE_FILE -C $CONFIG_FILE
		;;
	
	status)
		if [ -e $LOCK_FILE ]
		then
			echo "Sending SIGUSR1 to $SERVICE_NAME. Check the log for response."
			kill -s SIGUSR1 `cat $LOCK_FILE`
		else
			echo "Service $SERVICE_NAME does not seem to be running"
		fi
		;;
	
	status2)
		if [ -e $LOCK_FILE ]
		then
			echo "Sending SIGUSR2 to $SERVICE_NAME. Check the log for response."
			kill -s SIGUSR2 `cat $LOCK_FILE`
		else
			echo "Service $SERVICE_NAME does not seem to be running"
		fi
		;;
	
	*)
		echo "Usage: /etc/init.d/$SERVICE_NAME {start|stop|restart|force-restart|debug|status|status2}"
		exit 1
		;;
esac

exit 0
