#!/bin/bash
### BEGIN INIT INFO
# Provides:            xmemcached
# Required-Start:      $syslog
# Required-Stop:       $syslog
# Should-Start:        $local_fs
# Should-Stop:         $local_fs
# Default-Start:       2 3 4 5
# Default-Stop:                0 1 6
# Short-Description:   Start xmemcached daemon
# Description:         Start xmemcached daemon
### END INIT INFO 

SERVICE_PATH="/bin"
SERVICE_NAME="xmemcached"
SERVICE_FILE="$SERVICE_NAME.exe"
export MONO_OPTIONS=--runtime=v4.0.30319
export LD_LIBRARY_PATH=.:/usr/local/mono/2.8/lib/:$LD_LIBRARY_PATH

case "$1" in
	start)
		echo "Starting $SERVICE_NAME"
		mono-service2 -d:$SERVICE_PATH -l:/var/lock/$SERVICE_NAME.lock -m:$SERVICE_NAME $SERVICE_PATH/$SERVICE_FILE
		;;
		
	debug)
		echo "Starting $SERVICE_NAME"
		mono-service2 -d:$SERVICE_PATH -l:/var/lock/$SERVICE_NAME.lock -m:$SERVICE_NAME --debug $SERVICE_PATH/$SERVICE_FILE
		;;
		
	stop)
		echo "Stopping $SERVICE_NAME"
		kill `cat /var/lock/$SERVICE_NAME.lock`
		rm /var/lock/$SERVICE_NAME.lock
		;;
	
	restart)
		echo "Stopping $SERVICE_NAME"
		kill `cat /var/lock/$SERVICE_NAME.lock`
		rm /var/lock/$SERVICE_NAME.lock
		
		echo "Starting $SERVICE_NAME"
		mono-service2 -d:$SERVICE_PATH -l:/var/lock/$SERVICE_NAME.lock -m:$SERVICE_NAME $SERVICE_PATH/$SERVICE_FILE
		;;
	
	force-restart)
		echo "Forcing $SERVICE_NAME to stop"
		kill -s SIGKILL `cat /var/lock/$SERVICE_NAME.lock`
		rm /var/lock/$SERVICE_NAME.lock
		
		echo "Starting $SERVICE_NAME"
		mono-service2 -d:$SERVICE_PATH -l:/var/lock/$SERVICE_NAME.lock -m:$SERVICE_NAME $SERVICE_PATH/$SERVICE_FILE
		;;
	
	status)
		echo "Writing $SERVICE_NAME status to the log file"
		kill -s SIGUSR1 `cat /var/lock/$SERVICE_NAME.lock`
		;;
	
	*)
		echo "Usage: /etc/init.d/$SERVICE_NAME {start|stop|restart|force-restart|status}"
		exit 1
		;;
esac

exit 0
